// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class ActionPlans
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Deadline { get; set; }
        public DateTime SubmitDate { get; set; }
        public int ApprovedBy { get; set; }
        public int UserId { get; set; }
        public int DataId { get; set; }
        public int CommentId { get; set; }
        public string KpilevelCodeAndPeriod { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public bool ApprovedStatus { get; set; }
        public string Tag { get; set; }
        public DateTime CreateTime { get; set; }
        public int TagId { get; set; }
        public string Link { get; set; }
        public int Auditor { get; set; }
        public DateTime? UpdateSheduleDate { get; set; }
        public DateTime? ActualFinishDate { get; set; }
        public string KpilevelCode { get; set; }
    }
}