// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Data
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public string Period { get; set; }
        public int Year { get; set; }
        public DateTime CreateTime { get; set; }
        public string DateUpload { get; set; }
        public int Week { get; set; }
        public int Month { get; set; }
        public int Quarter { get; set; }
        public string KpilevelCode { get; set; }
        public string Remark { get; set; }
        public string Target { get; set; }
        public int Yearly { get; set; }
    }
}