// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Favourites
    {
        public int Id { get; set; }
        public string KpilevelCode { get; set; }
        public int UserId { get; set; }
        public DateTime CreateTime { get; set; }
        public string Period { get; set; }
    }
}