// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class MenuLangs
    {
        public int Id { get; set; }
        public string LangId { get; set; }
        public string Name { get; set; }
        public DateTime CreatedTime { get; set; }
        public int MenuId { get; set; }

        public virtual Menus Menu { get; set; }
    }
}