// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class NotificationDetails
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int NotificationId { get; set; }
        public bool Seen { get; set; }
        public DateTime CreateTime { get; set; }
        public string Action { get; set; }
        public string Content { get; set; }
        public string Url { get; set; }
    }
}