// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Occategories
    {
        public int Id { get; set; }
        public int Ocid { get; set; }
        public int CategoryId { get; set; }
        public bool Status { get; set; }
    }
}