// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Permissions
    {
        public int Id { get; set; }
        public string PermissionName { get; set; }
        public string Urldefault { get; set; }
    }
}