// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Resources
    {
        public int Id { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
        public bool State { get; set; }
        public int Permission { get; set; }
        public string FontAwesome { get; set; }
        public bool CheckRole { get; set; }
        public string BackgroudColor { get; set; }
        public int Menu { get; set; }
        public int UserId { get; set; }
    }
}