// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Revises
    {
        public int Id { get; set; }
        public string KpilevelCodePeriod { get; set; }
        public string PeriodValue { get; set; }
    }
}