// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class Roles
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    }
}