// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class StateSendMails
    {
        public int Id { get; set; }
        public DateTime ToDay { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
    }
}