// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProModes
{
    public partial class SubNotifications
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Kpiname { get; set; }
        public string Url { get; set; }
        public int UserId { get; set; }
        public int NotificationId { get; set; }

        public virtual Notifications Notification { get; set; }
    }
}